---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dikkie.
--- DateTime: 11/28/22 8:37 PM
---

v3 = {}
v3[1] = 0.4
v3[2] = 0.4
v3[3] = 0.4

setProperty(this, "diffuse", v3)

function render()
    shader.setProperty("diffuse", material.diffuse())
end