---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dikkie.
--- DateTime: 11/28/22 8:37 PM
---

setShaderProperty("model")
setShaderProperty("diffuse")
setShaderProperty("specular")
setShaderProperty("shininess")
setShaderProperty("viewPos")
setShaderProperty("invtransmodel")
